### PR TITLE
Issue #18: jsdom.env is not a function

### PR DESCRIPTION
**Pull request by kcbroomall**
Need to show path to old api.

### CODE REVIEW

**Comment by rstacruz** [comment]
At what jsdom version did this change start? We'll need to update the peerDependencies spec to suggest the correct jsdom version.

**Comment by RobLoach** [comment]
Works on `jsdom@~11.0.0` for me. Needed Node.js >6.

**Comment by mismatch** [comment]
@rstacruz It started at version 10.0.0 (see https://changelogs.md/github/tmpvar/jsdom/). Personally, I'd prefer mocha-jsdom to use new jsdom API as require("jsdom/lib/old-api.js") is temporary solution.

**Comment by RobLoach** [comment]
@mismatch Good find. Two things needed to update in this PR then....

1. Update `peerDependencies` to >=10.0.0
2. Update `.travis.yml` to use Node 6, 7 and 8

That should make the PR pass.

**Comment by jackpope** [comment]
@kcbroomall any update here? I've been hitting the same issue.

**Comment by RobLoach** [comment]
@jackpope @kcbroomall Updated PR is over at https://github.com/rstacruz/mocha-jsdom/issues/29 .
